const cities = [
  { label: "Ranchi, Jharkhand", value: "Ranchi" },
  { label: "Dhanbad, Jharkhand", value: "Dhanbad" },
  { label: "Jamshedpur, Jharkhand", value: "Jamshedpur" },
  { label: "Bokaro, Jharkhand", value: "Bokaro" },
  { label: "Hazaribagh, Jharkhand", value: "Hazaribagh" },
  { label: "Deoghar, Jharkhand", value: "Deoghar" },
  { label: "Giridih, Jharkhand", value: "Giridih" },
  { label: "Chaibasa, Jharkhand", value: "Chaibasa" },
  { label: "Ramgarh, Jharkhand", value: "Ramgarh" },

  { label: "Lucknow, Uttar Pradesh", value: "Lucknow" },
  { label: "Kanpur, Uttar Pradesh", value: "Kanpur" },
  { label: "Varanasi, Uttar Pradesh", value: "Varanasi" },
  { label: "Agra, Uttar Pradesh", value: "Agra" },
  { label: "Meerut, Uttar Pradesh", value: "Meerut" },
  { label: "Allahabad, Uttar Pradesh", value: "Allahabad" },
  { label: "Ghaziabad, Uttar Pradesh", value: "Ghaziabad" },
  { label: "Gorakhpur, Uttar Pradesh", value: "Gorakhpur" },
  { label: "Noida, Uttar Pradesh", value: "Noida" },
  { label: "Amethi, Uttar Pradesh", value: "Amethi" },

  { label: "Mumbai, Maharashtra", value: "Mumbai" },
  { label: "Pune, Maharashtra", value: "Pune" },
  { label: "Nagpur, Maharashtra", value: "Nagpur" },
  { label: "Nashik, Maharashtra", value: "Nashik" },
  { label: "Thane, Maharashtra", value: "Thane" },
  { label: "Aurangabad, Maharashtra", value: "Aurangabad" },
  { label: "Solapur, Maharashtra", value: "Solapur" },
  { label: "Amravati, Maharashtra", value: "Amravati" },
  { label: "Kolhapur, Maharashtra", value: "Kolhapur" },
  { label: "Latur, Maharashtra", value: "Latur" },

  { label: "Bengaluru, Karnataka", value: "Bengaluru" },
  { label: "Mysuru, Karnataka", value: "Mysuru" },
  { label: "Mangaluru, Karnataka", value: "Mangaluru" },
  { label: "Hubli, Karnataka", value: "Hubli" },
  { label: "Belgaum, Karnataka", value: "Belgaum" },
  { label: "Davangere, Karnataka", value: "Davangere" },
  { label: "Shivamogga, Karnataka", value: "Shivamogga" },
  { label: "Ballari, Karnataka", value: "Ballari" },
  { label: "Tumakuru, Karnataka", value: "Tumakuru" },
  { label: "Udupi, Karnataka", value: "Udupi" },

  { label: "Chennai, Tamil Nadu", value: "Chennai" },
  { label: "Coimbatore, Tamil Nadu", value: "Coimbatore" },
  { label: "Madurai, Tamil Nadu", value: "Madurai" },
  { label: "Tiruchirappalli, Tamil Nadu", value: "Tiruchirappalli" },
  { label: "Salem, Tamil Nadu", value: "Salem" },
  { label: "Vellore, Tamil Nadu", value: "Vellore" },
  { label: "Tirunelveli, Tamil Nadu", value: "Tirunelveli" },
  { label: "Erode, Tamil Nadu", value: "Erode" },
  { label: "Thoothukudi, Tamil Nadu", value: "Thoothukudi" },
  { label: "Dindigul, Tamil Nadu", value: "Dindigul" },
];

export default cities;
